ext/uv_devinfo: fix compile break cause by src/queue.h
In file included from /home/djz/workspace/test/m1_rel/nuttx/include/sys/boardctl.h:34,
                 from /home/djz/workspace/test/m1_rel/nuttx/include/nuttx/board.h:100,
                 from ext/src/uv_devinfo.c:23:
/home/djz/workspace/test/m1_rel/nuttx/include/nuttx/power/pm.h:157:21: error: field 'entry' has incomplete type
  157 |   struct dq_entry_s entry;   /* Supports a doubly linked list */
      |                     ^~~~~
/home/djz/workspace/test/m1_rel/nuttx/include/nuttx/power/pm.h:308:21: error: field 'node' has incomplete type
  308 |   struct dq_entry_s node;
      |                     ^~~~
/home/djz/workspace/test/m1_rel/nuttx/include/nuttx/power/pm.h:312:21: error: field 'fsnode' has incomplete type
  312 |   struct dq_entry_s fsnode;
      |                     ^~~~~~

Signed-off-by: Jiuzhu Dong <dongjiuzhu1@xiaomi.com>